# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

require 'rest-client'


u = User.create(username: "Maxwell", password:"1")

Comment.create(feedback: "No feedback")
Comment.create(feedback: "The line was too long")
Comment.create(feedback: "The line was okay")
Comment.create(feedback: "The line was short")
Comment.create(feedback: "No line!")
Comment.create(feedback: "The line was long, but moved quickly")
Comment.create(feedback: "The line was short, but moved slowly")







# Company.create(name: "Whole Foods Market")
# Store.create(name: "Whole Foods Tribeca", address: "270 Greenwich St, New York, NY 10007", company_id: 1)
# Store.create(name: "Whole Foods Bowery", address: "95 E Houston St, New York, NY 10002", company_id: 1)
# Store.create(name: "Whole Foods Chelsea", address: "250 7th Ave, New York, NY 10001", company_id: 1)
# Store.create(name: "Whole Foods Upper West Side", address: "808 Columbus Ave, New York, NY 10025", company_id: 1)
# Store.create(name: "Whole Foods Upper East Side", address: "1551 3rd Ave, New York, NY 10128", company_id: 1)
# Store.create(name: "Whole Foods Columbus Circle", address: "10 Columbus Cir sc101, New York, NY 10019", company_id: 1)
# Store.create(name: "Whole Foods Midtown East", address: "226 E 57th St, New York, NY 10022", company_id: 1)
# Store.create(name: "Whole Foods Williamsburg", address: "238 Bedford Ave, Brooklyn, NY 11249", company_id: 1)
# Store.create(name: "Whole Foods Ridgewood", address: "44 Godwin Ave, Ridgewood, NJ 07450", company_id: 1)
# Store.create(name: "Whole Foods Closter", address: "45 Vervalen St, Closter, NJ 07624", company_id: 1)
# Store.create(name: "Whole Foods Paramus", address: "300 Bergen Town Center, Paramus, NJ 07652", company_id: 1)
# Store.create(name: "Whole Foods Yonkers", address: "1 Ridge Hill Boulevard, Yonkers, NY 10710", company_id: 1)
# Store.create(name: "Whole Foods White Plains", address: "Fortunoff-Source At White Plns, 110 Bloomingdale Rd, White Plains, NY 10605", company_id: 1)
# Store.create(name: "Whole Foods Montclair", address: "701 Bloomfield Ave, Montclair, NJ 07042", company_id: 1)
# Store.create(name: "Whole Foods West Orange", address: "235 Prospect Ave, West Orange, NJ 07052", company_id: 1)
# Store.create(name: "Whole Foods Edgewater", address: "905 River Rd, Edgewater, NJ 07020", company_id: 1)
# Store.create(name: "Whole Foods Manhasset", address: "2101 Northern Blvd, Manhasset, NY 11030", company_id: 1)
# Store.create(name: "Whole Foods Milford", address: "1686 Boston Post Rd, Milford, CT 06460", company_id: 1)
# Store.create(name: "Whole Foods Newark", address: "633 Broad St, Newark, NJ 07102", company_id: 1)
# Store.create(name: "Whole Foods Greenwich", address: "633 Broad St, Newark, NJ 07102", company_id: 1)
# Store.create(name: "Whole Foods Morristown", address: "110 Washington St, Morristown, NJ 07960", company_id: 1)
# Store.create(name: "Whole Foods Madison", address: "222 Main St, Madison, NJ 07940", company_id: 1)
#
# Company.create(name: "Trader Joe's")
# Store.create(name: "Trader Joe's", address:"142 E 14th St, New York, NY 10003", company_id: 2)
# Store.create(name: "Trader Joe's", address:"675 6th Ave, New York, NY 10010", company_id: 2)
# Store.create(name: "Trader Joe's", address:"200 E 32nd St, New York, NY 10016", company_id: 2)
# Store.create(name: "Trader Joe's", address:"2073 Broadway, New York, NY 10023", company_id:2)
# Store.create(name: "Trader Joe's", address:"130 Court St, Brooklyn, NY 11201", company_id: 2)
# Store.create(name: "Trader Joe's", address:"1350 Willow Ave, Hoboken, NJ 07030", company_id: 2)
#
# Company.create(name: "Associated Supermarkets")
# Store.create(name: "Associated Supermarket", address:"755 Amsterdam Ave, New York, NY 10025", company_id: 3)
# Store.create(name: "Associated Supermarket", address:"409 E 14th St, New York, NY 10009", company_id:3)
# Store.create(name: "Associated Supermarket", address:"123 Avenue C, New York, NY 10009", company_id:3)
# Store.create(name: "Associated Supermarket", address:"13 W 100th St, New York, NY 10025", company_id:3)
# Store.create(name: "Associated Supermarket", address:"159-04 Harlem River Dr, New York, NY 10039", company_id:3)
#
# Company.create(name: "C-Town Supermarkets")
# Store.create(name: "C-Town", address:"1721 1st Avenue, New York, NY 10128", company_id:4)
# Store.create(name: "C-Town", address:"5 St James Pl, New York, NY 10038", company_id:4)
# Store.create(name: "C-Town", address:"4926 Broadway, New York, NY 10034", company_id:4)
# Store.create(name: "C-Town", address:"3320 Broadway, New York, NY 10031", company_id:4)
# Store.create(name: "C-Town", address:"1016 St Nicholas Ave, New York, NY 10032", company_id:4)
# Store.create(name: "C-Town", address:"188 Avenue C, New York, NY 10009", company_id:4)
# Store.create(name: "C-Town", address:"560 W 125th St, New York, NY 10027", company_id:4)
# Store.create(name: "C-Town", address:"3632 Broadway, New York, NY 10031", company_id:4)
# Store.create(name: "C-Town", address:"1314 St Nicholas Ave, New York, NY 10033", company_id:4)
# Store.create(name: "C-Town", address:"238 W 116th St, New York, NY 10026", company_id:4)
# Store.create(name: "C-Town", address:"2115 Pitkin Ave, Brooklyn, NY 11207", company_id:4)
# Store.create(name: "C-Town", address:"330 Graham Ave, Brooklyn, NY 11211", company_id:4)
# Store.create(name: "C-Town", address:"40-12 28th Ave, Astoria, NY 11103", company_id:4)
# Store.create(name: "C-Town", address:"75-43 Metropolitan Ave, Queens, NY 11379", company_id:4)
# Store.create(name: "C-Town", address:"953 Manhattan Ave, Brooklyn, NY 11222", company_id:4)
# Store.create(name: "C-Town", address:"130 Havemeyer St, Brooklyn, NY 11211", company_id:4)
# Store.create(name: "C-Town", address:"21-30 Newtown Ave, Astoria, NY 11102", company_id:4)
# Store.create(name: "C-Town", address:"41-25 Greenpoint Ave, Long Island City, NY 11104", company_id:4)
# Store.create(name: "C-Town", address:"6614 18th Ave, Brooklyn, NY 11204", company_id:4)
#
# Company.create(name: "Gristede's Foods")
# Store.create(name: "Gristede's", address:"1365 3rd Ave, New York, NY 10075", company_id:5)
# Store.create(name: "Gristede's", address:"2704 Broadway, New York, NY 10025", company_id:5)
# Store.create(name: "Gristede's", address:"4037 Broadway, New York, NY 10032", company_id:5)
# Store.create(name: "Gristede's", address:"221 8th Ave, New York, NY 10011", company_id:5)
# Store.create(name: "Gristede's", address:"504 Columbus Ave, New York, NY 10024", company_id:5)
# Store.create(name: "Gristede's", address:"246 Mercer St, New York, NY 10012", company_id:5)
# Store.create(name: "Gristede's", address:"1446 2nd Ave, New York, NY 10075", company_id:5)
# Store.create(name: "Gristede's", address:"90 Maiden Ln, New York, NY 10038", company_id:5)
# Store.create(name: "Gristede's", address:"1208 1st Avenue, New York, NY 10065", company_id:5)
# Store.create(name: "Gristede's", address:"315 South End Ave, New York, NY 10280", company_id:5)
# Store.create(name: "Gristede's", address:"225 9th Ave, New York, NY 10011", company_id:5)
# Store.create(name: "Gristede's", address:"25 Waterside Plaza, New York, NY 10010", company_id:5)
# Store.create(name: "Gristede's", address:"1644 York Ave, New York, NY 10028", company_id:5)
# Store.create(name: "Gristede's", address:"307 W 26th St, New York, NY 10001", company_id:5)
# Store.create(name: "Gristede's", address:"686 Main St, New York, NY 10044", company_id:5)
# Store.create(name: "Gristede's", address:"355 1st Avenue, New York, NY 10003", company_id:5)
# Store.create(name: "Gristede's", address:"907 8th Ave, New York, NY 10019", company_id:5)
# Store.create(name: "Gristede's", address:"3 Sheridan Square, New York, NY 10014", company_id:5)
# Store.create(name: "Gristede's", address:"1343 Lexington Ave, New York, NY 10128", company_id:5)
# Store.create(name: "Gristede's", address:"748 2nd Ave, New York, NY 10017", company_id:5)
#
# Company.create(name: "Citarella Gourmet Market")
# Store.create(name: "Citarella Gourmet Market", address:"1313 3rd Ave, New York, NY 10021", company_id:6)
# Store.create(name: "Citarella Gourmet Market", address:"2135 Broadway, New York, NY 10023", company_id:6)
# Store.create(name: "Citarella Gourmet Market", address:"424 6th Ave, New York, NY 10011", company_id:6)
#
# Company.create(name: "Fairway Market")
# Store.create(name: "Fairway", address:"550 2nd Ave, New York, NY 10016", company_id:7)
# Store.create(name: "Fairway", address:"2131 Broadway, New York, NY 10023", company_id:7)
# Store.create(name: "Fairway", address:"766 6th Ave, New York, NY 10010", company_id:7)
# Store.create(name: "Fairway", address:"2328 12th Ave, New York, NY 10027", company_id:7)
# Store.create(name: "Fairway", address:"240 E 86th St, New York, NY 10028", company_id:7)
# Store.create(name: "Fairway", address:"480-500 Van Brunt St, Brooklyn, NY 11231", company_id:7)
# Store.create(name: "Fairway", address:"2149 Ralph Ave, Brooklyn, NY 11234", company_id:7)
# Store.create(name: "Fairway", address:"847 Pelham Pkwy, Pelham, NY 10803", company_id:7)
#
# Company.create(name: "D'Agostino")
# Store.create(name: "D'Agostino", address:"1074 Lexington Ave, New York, NY 10021", company_id:8)
# Store.create(name: "D'Agostino", address:"341 3rd Ave, New York, NY 10010", company_id:8)
# Store.create(name: "D'Agostino", address:"633 Columbus Ave, New York, NY 10024", company_id:8)
# Store.create(name: "D'Agostino", address:"790 Greenwich St #1, New York, NY 10014", company_id:8)
# Store.create(name: "D'Agostino", address:"815 10th Ave, New York, NY 10019", company_id:8)
# Store.create(name: "D'Agostino", address:"528 3rd Ave, New York, NY 10016", company_id:8)
# Store.create(name: "D'Agostino", address:"1507 York Ave, New York, NY 10075", company_id:8)
# Store.create(name: "D'Agostino", address:"966 1st Avenue, New York, NY 10022", company_id:8)
#
# Company.create(name: "Subway")
# Store.create(name: "Subway", address:"11 Broadway Unit #155, New York, NY 10004", company_id:9)
# Store.create(name: "Subway", address:"30 Broad St, New York, NY 10004", company_id:9)
#
# Company.create(name: "Burger King")
# Store.create(name: "Burger King", address:"16 Beaver St, New York, NY 10004", company_id:10)
#
# Company.create(name: "Chipotle")
# Store.create(name: "Chipotle", address:"2 Broadway, New York, NY 10004", company_id:11)
#
# Company.create(name: "Pret A Manger")
# Store.create(name: "Pret A Manger", address:"50 Broadway, New York, NY 10004", company_id:12)
